### ISSUE TITLE
LetsEncrypt support for Mail & AdminInterface

### ISSUE THREAD

**Issue by schulluk** [niiknow/vestacp#10]
Is it planned to automatically generate LetsEncrypt certificates for the mail server and admin interface?

**Comment by noogen** [comment]
Yes, but It hasn't been on my priority because we use purchased SSL in our Production.

Something like this?  https://forum.vestacp.com/viewtopic.php?f=19&t=13057

Lets brainstorm.   Problem is, we do not know the domain that Vesta will be using.  Should we request a docker environment variable for this domain/hostname or $VESTA_DOMAIN?

The init script would check:
1. if exists $VESTA_DOMAIN, setup domain on the admin account and acquire Letsencrypt SSL.
2. link the SSL to vesta admin and exim4.
3. link for any other service that require the SSL too?

Someone has to test this feature since I don't really use Vesta for email.

**Comment by schulluk** [comment]
Maybe we could reuse the hostname provided to start the docker container.
My main purpose for this container is running a mail server in docker.

Unfortunately it's not (easily) possible to change the hostname of a docker container while running it. But you can provide an own hostname during startup which solves this problem.

Therefore, we could just fallback to the hostname and have a $VESTA_DOMAIN in case someone wants to overwrite it with another value.
What do you think?

As an example for the hostname, here is my docker-compose.yml:

```
vestacp:
  container_name: vestacp
  hostname: my-domain.com
  image: niiknow/vestacp
  restart: always
  ports:
    - "25:25"
    - "110:110"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    - "995:995"
    - "8083:8083"
  expose:
    - "80"
  volumes:
    - /opt/data/mail/vestacp/vesta:/vesta:rw
    - /opt/data/mail/vestacp/home:/home:rw
    - /opt/data/mail/vestacp/backup:/backup:rw
```
