### ISSUE TITLE
Problems with configuration

### ISSUE THREAD

**Issue by danipolo** [niiknow/vestacp#18]
I found this awesome project today. I'm trying to deploy it but maybe it's a lack of configuration.

How can I add the IP's into the system? I have several IP's bind to the host machine but I don't know how to map them inside. What's the process to replace your demo domain to a real domain?

Some help on README will be appreciated :)

**Comment by noogen** [comment]
IP address is specified by your docker run config: https://blog.jessfraz.com/post/ips-for-all-the-things/ or docker-compose config.  It has nothing to do with the container.  At the present time, vestacp container only support one IP and that's why it's default to 127.0.0.1 or 0.0.0.0.  This is because complexity of having multiple IP inside a container: https://forums.docker.com/t/docker-container-having-multiple-ips/33105/5

Alternatively, both options are pretty networking and nginx knowledge intensive to do:
1.  You would need to run multiple vestacp container and map different IP to each.
2.  Run nginx proxy from specific ip to specific port

The demo domain is added during the installation of Vesta.  I really can't do anything about that with the exception of trying to automate it removal with a script after Vesta installation, which you can manually.

This panel does support auto custom domain ssl: https://github.com/niiknow/vestacp/blob/master/rootfs/sysprepz/admin/bin/vesta-auto-ssl.sh

You just need to pass in VESTA_DOMAIN environment variable.  Also note that, *service vesta restart* is needed every now and then to reload the new letsencrypt autossl if you find that it has expired.  The new SSL is there, it's just not loaded.   This is because the renewal is based on the builtin letsencrypt process, which doesn't expect the panel ssl to be renewed.   I can work on automating this in the future.

**Comment by danipolo** [comment]
Thank you! Awesome!

I think most of problems right now is coming from DNS. I tried to remove the example domain and all crashed when I enable:

```
&& ./exim4 start \
&& ./dovecot start \
&& ./clamav-daemon start \
&& ./spamassassin start \
&& ./php7.1-fpm start \
```

What's the process to enable DNS? I'm currently running Vesta on a subdomain (hosting.example.com) with own dedicated IP (I modified the docker-compose):

```
version: '2'

services:
  vesta:
    image: niiknow/vestacp:0.9.25
    container_name: vesta
    cap_add: ['NET_RAW', 'NET_ADMIN']
    volumes:
      - "./backup:/backup"
      - "./vesta:/vesta"
      - "./home:/home"
    ports:
      - "123.123.123.123:22:22"
      - "123.123.123.123:80:80"
      - "123.123.123.123:443:443"
      - "123.123.123.123:8083:8083"
    labels:
      - "Vesta Control Panel"
    restart: unless-stopped
    environment:
      - VESTA_DOMAIN=hosting.example.com
```

I pointed an A to **ns1.example.com** and **ns2.example.com** to the same IP. What I'm doing wrong? All crashed when I remove the example domain :(
