### ISSUE TITLE
Admin UI down using specific IP

### ISSUE THREAD

**Issue by phoenixsampras** [niiknow/vestacp#55]
Hello,

Installed the using docker-compose as per the instructions, modified the yml as follows.

However the 8083 port is not open, I'm assigning a specific IP to the forwarded ports, anything else I can do to enable the admin interface??

Thanks in advance

```
version: "2"

services:
  vesta:
    image: niiknow/vestacp
    container_name: vesta
    volumes:
      - "/data1/vestacp/backup:/backup"
      - "/data1/vestacp/vesta:/vesta"
      - "/data1/vestacp/home:/home"
    ports:
      - "8.8.8.8:2222:22"
      - "8.8.8.8:2121:21"
      - "8.8.8.8:53:53"
      - "8.8.8.8:81:80"
      - "8.8.8.8:444:443"
      - "8.8.8.8:3307:3306"
      - "8.8.8.8:8083:8083"
    privileged: true
    labels:
      - "Vesta Control Panel"
    restart: unless-stopped

    networks:
      vesta_network1:
        ipv4_address: 172.54.54.2
networks:
  vesta_network1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.54.54.0/24
          gateway: 172.54.54.1

```
