### ISSUE TITLE
mysql fail start

### ISSUE THREAD

**Issue by receperdogan** [niiknow/vestacp#93]
Hi,
When i trying to run the image with yml, i m getting this, rest of log is good.
```
Starting MariaDB database server mysqld
   ...fail!
```
After that, container runs up, but i cant start mysql. Mysql error logs show nothing.
Any help?

  
**Edit :** 
On my last test  your YML file is working good but mine is not. After containers up, mysql is not working. 

```
version: "3.7"
services:
  vcp:
    image: niiknow/vestacp
    hostname: ABWB
    volumes:
      - type: volume
        source: vesta-backup
        target: /backup
        volume:
          nocopy: true
      - type: volume
        source: vesta-vesta
        target: /vesta
        volume:
          nocopy: true
      - type: volume
        source: vesta-home
        target: /home
        volume:
          nocopy: true
    ports:
      - "3322:22"
      - "80:80"
      - "443:443"
      - "9088:8083"
    labels:
      - "Vesta Control Panel"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 10
volumes:
  vesta-backup:
  vesta-vesta:
  vesta-home:
```
 
**Edit  2:**

I think i found the problem, it is about replicas size. 1 Replica is working good, more is not.
When i incrise replica size more than 1, mysql  not starting.

Any help?
